######################################################################
#  Makefile.incl
######################################################################

YACC	= bison
FLEX	= flex

CSTD	?= -std=c++0x
OPTZ	?= -O0 -g

CXX	= g++
CC	= gcc

GNAT	= gnatmake
GNATOPTS = -Wall

# End Makefile.incl
